# =========================
# APP
# =========================
server.port=8080

# =========================
# DATABASE (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/cotizador
spring.datasource.username=postgres
spring.datasource.password=1234

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# (Opcional pero recomendado para PostgreSQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# LIMITES REQUEST (IMPORTANTE PARA BASE64)
# =========================
# Si envías PDFs en Base64 por JSON, el body puede ser grande.
# Ajusta según el tamaño de tus contratos.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB

# =========================
# CARGA MASIVA (PARA DESPUÉS)
# =========================
contracts.bulk-load=false
contracts.base-path=C:/contratos-isapre
